import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const Montserrat_init = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Eduardo Maroto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Portfolio Eduardo Maroto</title>
      </head>
      <body className={Montserrat_init.className}>{children}
      </body>
    </html>
  );
}
